/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/bill/': RouteRecordInfo<'/bill/', '/bill', Record<never, never>, Record<never, never>>,
    '/bill/components/AiAssistantPanel': RouteRecordInfo<'/bill/components/AiAssistantPanel', '/bill/components/AiAssistantPanel', Record<never, never>, Record<never, never>>,
    '/bill/components/BillAddPanel': RouteRecordInfo<'/bill/components/BillAddPanel', '/bill/components/BillAddPanel', Record<never, never>, Record<never, never>>,
    '/bill/components/BillHeader': RouteRecordInfo<'/bill/components/BillHeader', '/bill/components/BillHeader', Record<never, never>, Record<never, never>>,
    '/bill/components/BillImportPanel': RouteRecordInfo<'/bill/components/BillImportPanel', '/bill/components/BillImportPanel', Record<never, never>, Record<never, never>>,
    '/bill/components/BillList': RouteRecordInfo<'/bill/components/BillList', '/bill/components/BillList', Record<never, never>, Record<never, never>>,
    '/bill/components/DataOverview': RouteRecordInfo<'/bill/components/DataOverview', '/bill/components/DataOverview', Record<never, never>, Record<never, never>>,
    '/personal/': RouteRecordInfo<'/personal/', '/personal', Record<never, never>, Record<never, never>>,
    '/personal/analyse': RouteRecordInfo<'/personal/analyse', '/personal/analyse', Record<never, never>, Record<never, never>>,
    '/personal/develop': RouteRecordInfo<'/personal/develop', '/personal/develop', Record<never, never>, Record<never, never>>,
    '/personal/edit': RouteRecordInfo<'/personal/edit', '/personal/edit', Record<never, never>, Record<never, never>>,
    '/personal/settings': RouteRecordInfo<'/personal/settings', '/personal/settings', Record<never, never>, Record<never, never>>,
  }
}
